apiVersion: v1
kind: Service
metadata:
  name: geological-sample-api
  namespace: geological-sample-api
  labels:
    app: geological-sample-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: geological-sample-api
